//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace PackTwo.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SFBoxSoap", Namespace="http://dyrj.net/")]
    public partial class SFBox : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductInfoByXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckBindDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDistrictInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNetSiteInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewBoxNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetBoxStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateEncasementBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateEncasementBillByXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckBoxNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOutStockBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSystemTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOutStockNoticesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOutStockNoticeDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnLockStockNoticeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SFBox() {
            this.Url = global::PackTwo.Properties.Settings.Default.PackTwo_WebReference_SFBox;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event GetProductInfoCompletedEventHandler GetProductInfoCompleted;
        
        /// <remarks/>
        public event GetProductInfoByXMLCompletedEventHandler GetProductInfoByXMLCompleted;
        
        /// <remarks/>
        public event CheckBindDataCompletedEventHandler CheckBindDataCompleted;
        
        /// <remarks/>
        public event GetDistrictInfoCompletedEventHandler GetDistrictInfoCompleted;
        
        /// <remarks/>
        public event GetNetSiteInfoCompletedEventHandler GetNetSiteInfoCompleted;
        
        /// <remarks/>
        public event GetDepartmentInfoCompletedEventHandler GetDepartmentInfoCompleted;
        
        /// <remarks/>
        public event GetNewBoxNoCompletedEventHandler GetNewBoxNoCompleted;
        
        /// <remarks/>
        public event ResetBoxStatusCompletedEventHandler ResetBoxStatusCompleted;
        
        /// <remarks/>
        public event CreateEncasementBillCompletedEventHandler CreateEncasementBillCompleted;
        
        /// <remarks/>
        public event CreateEncasementBillByXmlCompletedEventHandler CreateEncasementBillByXmlCompleted;
        
        /// <remarks/>
        public event CheckBoxNoCompletedEventHandler CheckBoxNoCompleted;
        
        /// <remarks/>
        public event CreateOutStockBillCompletedEventHandler CreateOutStockBillCompleted;
        
        /// <remarks/>
        public event GetSystemTimeCompletedEventHandler GetSystemTimeCompleted;
        
        /// <remarks/>
        public event GetOutStockNoticesCompletedEventHandler GetOutStockNoticesCompleted;
        
        /// <remarks/>
        public event GetOutStockNoticeDetailCompletedEventHandler GetOutStockNoticeDetailCompleted;
        
        /// <remarks/>
        public event UnLockStockNoticeCompletedEventHandler UnLockStockNoticeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/Login", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login(string UserName, string Password) {
            object[] results = this.Invoke("Login", new object[] {
                        UserName,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string UserName, string Password) {
            this.LoginAsync(UserName, Password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string UserName, string Password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        UserName,
                        Password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/GetProductInfo", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetProductInfo() {
            object[] results = this.Invoke("GetProductInfo", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductInfoAsync() {
            this.GetProductInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetProductInfoAsync(object userState) {
            if ((this.GetProductInfoOperationCompleted == null)) {
                this.GetProductInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductInfoOperationCompleted);
            }
            this.InvokeAsync("GetProductInfo", new object[0], this.GetProductInfoOperationCompleted, userState);
        }
        
        private void OnGetProductInfoOperationCompleted(object arg) {
            if ((this.GetProductInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductInfoCompleted(this, new GetProductInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/GetProductInfoByXML", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetProductInfoByXML() {
            object[] results = this.Invoke("GetProductInfoByXML", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductInfoByXMLAsync() {
            this.GetProductInfoByXMLAsync(null);
        }
        
        /// <remarks/>
        public void GetProductInfoByXMLAsync(object userState) {
            if ((this.GetProductInfoByXMLOperationCompleted == null)) {
                this.GetProductInfoByXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductInfoByXMLOperationCompleted);
            }
            this.InvokeAsync("GetProductInfoByXML", new object[0], this.GetProductInfoByXMLOperationCompleted, userState);
        }
        
        private void OnGetProductInfoByXMLOperationCompleted(object arg) {
            if ((this.GetProductInfoByXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductInfoByXMLCompleted(this, new GetProductInfoByXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/CheckBindData", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckBindData(string SNs) {
            object[] results = this.Invoke("CheckBindData", new object[] {
                        SNs});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckBindDataAsync(string SNs) {
            this.CheckBindDataAsync(SNs, null);
        }
        
        /// <remarks/>
        public void CheckBindDataAsync(string SNs, object userState) {
            if ((this.CheckBindDataOperationCompleted == null)) {
                this.CheckBindDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckBindDataOperationCompleted);
            }
            this.InvokeAsync("CheckBindData", new object[] {
                        SNs}, this.CheckBindDataOperationCompleted, userState);
        }
        
        private void OnCheckBindDataOperationCompleted(object arg) {
            if ((this.CheckBindDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckBindDataCompleted(this, new CheckBindDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/GetDistrictInfo", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDistrictInfo() {
            object[] results = this.Invoke("GetDistrictInfo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDistrictInfoAsync() {
            this.GetDistrictInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetDistrictInfoAsync(object userState) {
            if ((this.GetDistrictInfoOperationCompleted == null)) {
                this.GetDistrictInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDistrictInfoOperationCompleted);
            }
            this.InvokeAsync("GetDistrictInfo", new object[0], this.GetDistrictInfoOperationCompleted, userState);
        }
        
        private void OnGetDistrictInfoOperationCompleted(object arg) {
            if ((this.GetDistrictInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDistrictInfoCompleted(this, new GetDistrictInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/GetNetSiteInfo", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetNetSiteInfo(string DistrictNo) {
            object[] results = this.Invoke("GetNetSiteInfo", new object[] {
                        DistrictNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNetSiteInfoAsync(string DistrictNo) {
            this.GetNetSiteInfoAsync(DistrictNo, null);
        }
        
        /// <remarks/>
        public void GetNetSiteInfoAsync(string DistrictNo, object userState) {
            if ((this.GetNetSiteInfoOperationCompleted == null)) {
                this.GetNetSiteInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNetSiteInfoOperationCompleted);
            }
            this.InvokeAsync("GetNetSiteInfo", new object[] {
                        DistrictNo}, this.GetNetSiteInfoOperationCompleted, userState);
        }
        
        private void OnGetNetSiteInfoOperationCompleted(object arg) {
            if ((this.GetNetSiteInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNetSiteInfoCompleted(this, new GetNetSiteInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/GetDepartmentInfo", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDepartmentInfo() {
            object[] results = this.Invoke("GetDepartmentInfo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentInfoAsync() {
            this.GetDepartmentInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetDepartmentInfoAsync(object userState) {
            if ((this.GetDepartmentInfoOperationCompleted == null)) {
                this.GetDepartmentInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentInfoOperationCompleted);
            }
            this.InvokeAsync("GetDepartmentInfo", new object[0], this.GetDepartmentInfoOperationCompleted, userState);
        }
        
        private void OnGetDepartmentInfoOperationCompleted(object arg) {
            if ((this.GetDepartmentInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentInfoCompleted(this, new GetDepartmentInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/GetNewBoxNo", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetNewBoxNo() {
            object[] results = this.Invoke("GetNewBoxNo", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewBoxNoAsync() {
            this.GetNewBoxNoAsync(null);
        }
        
        /// <remarks/>
        public void GetNewBoxNoAsync(object userState) {
            if ((this.GetNewBoxNoOperationCompleted == null)) {
                this.GetNewBoxNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewBoxNoOperationCompleted);
            }
            this.InvokeAsync("GetNewBoxNo", new object[0], this.GetNewBoxNoOperationCompleted, userState);
        }
        
        private void OnGetNewBoxNoOperationCompleted(object arg) {
            if ((this.GetNewBoxNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewBoxNoCompleted(this, new GetNewBoxNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/ResetBoxStatus", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object ResetBoxStatus(string BoxSN) {
            object[] results = this.Invoke("ResetBoxStatus", new object[] {
                        BoxSN});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void ResetBoxStatusAsync(string BoxSN) {
            this.ResetBoxStatusAsync(BoxSN, null);
        }
        
        /// <remarks/>
        public void ResetBoxStatusAsync(string BoxSN, object userState) {
            if ((this.ResetBoxStatusOperationCompleted == null)) {
                this.ResetBoxStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetBoxStatusOperationCompleted);
            }
            this.InvokeAsync("ResetBoxStatus", new object[] {
                        BoxSN}, this.ResetBoxStatusOperationCompleted, userState);
        }
        
        private void OnResetBoxStatusOperationCompleted(object arg) {
            if ((this.ResetBoxStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetBoxStatusCompleted(this, new ResetBoxStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/CreateEncasementBill", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateEncasementBill(System.Data.DataSet ds) {
            this.Invoke("CreateEncasementBill", new object[] {
                        ds});
        }
        
        /// <remarks/>
        public void CreateEncasementBillAsync(System.Data.DataSet ds) {
            this.CreateEncasementBillAsync(ds, null);
        }
        
        /// <remarks/>
        public void CreateEncasementBillAsync(System.Data.DataSet ds, object userState) {
            if ((this.CreateEncasementBillOperationCompleted == null)) {
                this.CreateEncasementBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateEncasementBillOperationCompleted);
            }
            this.InvokeAsync("CreateEncasementBill", new object[] {
                        ds}, this.CreateEncasementBillOperationCompleted, userState);
        }
        
        private void OnCreateEncasementBillOperationCompleted(object arg) {
            if ((this.CreateEncasementBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateEncasementBillCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/CreateEncasementBillByXml", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateEncasementBillByXml(string xml) {
            this.Invoke("CreateEncasementBillByXml", new object[] {
                        xml});
        }
        
        /// <remarks/>
        public void CreateEncasementBillByXmlAsync(string xml) {
            this.CreateEncasementBillByXmlAsync(xml, null);
        }
        
        /// <remarks/>
        public void CreateEncasementBillByXmlAsync(string xml, object userState) {
            if ((this.CreateEncasementBillByXmlOperationCompleted == null)) {
                this.CreateEncasementBillByXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateEncasementBillByXmlOperationCompleted);
            }
            this.InvokeAsync("CreateEncasementBillByXml", new object[] {
                        xml}, this.CreateEncasementBillByXmlOperationCompleted, userState);
        }
        
        private void OnCreateEncasementBillByXmlOperationCompleted(object arg) {
            if ((this.CreateEncasementBillByXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateEncasementBillByXmlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/CheckBoxNo", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckBoxNo(string BoxNo) {
            object[] results = this.Invoke("CheckBoxNo", new object[] {
                        BoxNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckBoxNoAsync(string BoxNo) {
            this.CheckBoxNoAsync(BoxNo, null);
        }
        
        /// <remarks/>
        public void CheckBoxNoAsync(string BoxNo, object userState) {
            if ((this.CheckBoxNoOperationCompleted == null)) {
                this.CheckBoxNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckBoxNoOperationCompleted);
            }
            this.InvokeAsync("CheckBoxNo", new object[] {
                        BoxNo}, this.CheckBoxNoOperationCompleted, userState);
        }
        
        private void OnCheckBoxNoOperationCompleted(object arg) {
            if ((this.CheckBoxNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckBoxNoCompleted(this, new CheckBoxNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/CreateOutStockBill", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateOutStockBill(string UserNo, string NetSiteNo, string OutStockNoticeID, string BoxesNo, string BoxesSN) {
            object[] results = this.Invoke("CreateOutStockBill", new object[] {
                        UserNo,
                        NetSiteNo,
                        OutStockNoticeID,
                        BoxesNo,
                        BoxesSN});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOutStockBillAsync(string UserNo, string NetSiteNo, string OutStockNoticeID, string BoxesNo, string BoxesSN) {
            this.CreateOutStockBillAsync(UserNo, NetSiteNo, OutStockNoticeID, BoxesNo, BoxesSN, null);
        }
        
        /// <remarks/>
        public void CreateOutStockBillAsync(string UserNo, string NetSiteNo, string OutStockNoticeID, string BoxesNo, string BoxesSN, object userState) {
            if ((this.CreateOutStockBillOperationCompleted == null)) {
                this.CreateOutStockBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOutStockBillOperationCompleted);
            }
            this.InvokeAsync("CreateOutStockBill", new object[] {
                        UserNo,
                        NetSiteNo,
                        OutStockNoticeID,
                        BoxesNo,
                        BoxesSN}, this.CreateOutStockBillOperationCompleted, userState);
        }
        
        private void OnCreateOutStockBillOperationCompleted(object arg) {
            if ((this.CreateOutStockBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOutStockBillCompleted(this, new CreateOutStockBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/GetSystemTime", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSystemTime() {
            object[] results = this.Invoke("GetSystemTime", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSystemTimeAsync() {
            this.GetSystemTimeAsync(null);
        }
        
        /// <remarks/>
        public void GetSystemTimeAsync(object userState) {
            if ((this.GetSystemTimeOperationCompleted == null)) {
                this.GetSystemTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSystemTimeOperationCompleted);
            }
            this.InvokeAsync("GetSystemTime", new object[0], this.GetSystemTimeOperationCompleted, userState);
        }
        
        private void OnGetSystemTimeOperationCompleted(object arg) {
            if ((this.GetSystemTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSystemTimeCompleted(this, new GetSystemTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/GetOutStockNotices", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetOutStockNotices() {
            object[] results = this.Invoke("GetOutStockNotices", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetOutStockNoticesAsync() {
            this.GetOutStockNoticesAsync(null);
        }
        
        /// <remarks/>
        public void GetOutStockNoticesAsync(object userState) {
            if ((this.GetOutStockNoticesOperationCompleted == null)) {
                this.GetOutStockNoticesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOutStockNoticesOperationCompleted);
            }
            this.InvokeAsync("GetOutStockNotices", new object[0], this.GetOutStockNoticesOperationCompleted, userState);
        }
        
        private void OnGetOutStockNoticesOperationCompleted(object arg) {
            if ((this.GetOutStockNoticesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOutStockNoticesCompleted(this, new GetOutStockNoticesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/GetOutStockNoticeDetail", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetOutStockNoticeDetail(string MachineID, string OutStockNoticeID) {
            object[] results = this.Invoke("GetOutStockNoticeDetail", new object[] {
                        MachineID,
                        OutStockNoticeID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetOutStockNoticeDetailAsync(string MachineID, string OutStockNoticeID) {
            this.GetOutStockNoticeDetailAsync(MachineID, OutStockNoticeID, null);
        }
        
        /// <remarks/>
        public void GetOutStockNoticeDetailAsync(string MachineID, string OutStockNoticeID, object userState) {
            if ((this.GetOutStockNoticeDetailOperationCompleted == null)) {
                this.GetOutStockNoticeDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOutStockNoticeDetailOperationCompleted);
            }
            this.InvokeAsync("GetOutStockNoticeDetail", new object[] {
                        MachineID,
                        OutStockNoticeID}, this.GetOutStockNoticeDetailOperationCompleted, userState);
        }
        
        private void OnGetOutStockNoticeDetailOperationCompleted(object arg) {
            if ((this.GetOutStockNoticeDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOutStockNoticeDetailCompleted(this, new GetOutStockNoticeDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dyrj.net/UnLockStockNotice", RequestNamespace="http://dyrj.net/", ResponseNamespace="http://dyrj.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UnLockStockNotice(string MachineID, string OutStockNoticeID) {
            object[] results = this.Invoke("UnLockStockNotice", new object[] {
                        MachineID,
                        OutStockNoticeID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UnLockStockNoticeAsync(string MachineID, string OutStockNoticeID) {
            this.UnLockStockNoticeAsync(MachineID, OutStockNoticeID, null);
        }
        
        /// <remarks/>
        public void UnLockStockNoticeAsync(string MachineID, string OutStockNoticeID, object userState) {
            if ((this.UnLockStockNoticeOperationCompleted == null)) {
                this.UnLockStockNoticeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnLockStockNoticeOperationCompleted);
            }
            this.InvokeAsync("UnLockStockNotice", new object[] {
                        MachineID,
                        OutStockNoticeID}, this.UnLockStockNoticeOperationCompleted, userState);
        }
        
        private void OnUnLockStockNoticeOperationCompleted(object arg) {
            if ((this.UnLockStockNoticeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnLockStockNoticeCompleted(this, new UnLockStockNoticeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetProductInfoCompletedEventHandler(object sender, GetProductInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetProductInfoByXMLCompletedEventHandler(object sender, GetProductInfoByXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductInfoByXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductInfoByXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CheckBindDataCompletedEventHandler(object sender, CheckBindDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckBindDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckBindDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetDistrictInfoCompletedEventHandler(object sender, GetDistrictInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDistrictInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDistrictInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetNetSiteInfoCompletedEventHandler(object sender, GetNetSiteInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNetSiteInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNetSiteInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetDepartmentInfoCompletedEventHandler(object sender, GetDepartmentInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetNewBoxNoCompletedEventHandler(object sender, GetNewBoxNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewBoxNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewBoxNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ResetBoxStatusCompletedEventHandler(object sender, ResetBoxStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResetBoxStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResetBoxStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateEncasementBillCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateEncasementBillByXmlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CheckBoxNoCompletedEventHandler(object sender, CheckBoxNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckBoxNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckBoxNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateOutStockBillCompletedEventHandler(object sender, CreateOutStockBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOutStockBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOutStockBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetSystemTimeCompletedEventHandler(object sender, GetSystemTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSystemTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSystemTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetOutStockNoticesCompletedEventHandler(object sender, GetOutStockNoticesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOutStockNoticesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOutStockNoticesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetOutStockNoticeDetailCompletedEventHandler(object sender, GetOutStockNoticeDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOutStockNoticeDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOutStockNoticeDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UnLockStockNoticeCompletedEventHandler(object sender, UnLockStockNoticeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnLockStockNoticeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UnLockStockNoticeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591